---
- ec2_group_facts:
    filters:
      vpc-id: "{{ aws_sg_vpc_id }}"
    profile: "{{ aws_security_groups_profile }}"
    region: "{{ aws_security_groups_region }}"
  register: ec2_group_result

- name: delete security groups
  ec2_group:
    group_id: "{{ item.group_id }}"
    profile: "{{ aws_security_groups_profile }}"
    region: "{{ aws_security_groups_region }}"
    state: absent
  loop_control:
    label: "{{ item.group_name }}"
  when: item.group_name != 'default'
  with_items: "{{ ec2_group_result.security_groups }}"
