---
- block:

  - name: set hostname
    hostname:
      name: "{{ inventory_hostname_short }}"

  - name: update /etc/hosts
    lineinfile:
      dest: /etc/hosts
      regexp: '^127.0.0.1[ \t]+localhost'
      line: '127.0.0.1 localhost {{ inventory_hostname }} {{ inventory_hostname_short }}'
      state: present

  become: true
