---
- block:

  - name: install pip
    apt:
      name: "{{ item }}"
      install_recommends: no
      state: present
    with_items:
      - python3-pip

  - name: install docker-py using pip
    pip:
      name: docker

  become: true
