---
- block:

  - name: create /etc/demokit/certs/{{ inventory_hostname }}
    file:
      path: /etc/demokit/certs/{{ inventory_hostname }}
      state: directory

  - name: copy private key to {{ inventory_hostname }}
    copy:
      src: ../../../demos/certs/{{ inventory_hostname }}/key.pem
      dest: /etc/demokit/certs/{{ inventory_hostname }}/key.pem

  - name: copy certificate to {{ inventory_hostname }}
    copy:
      src: ../../../demos/certs/{{ inventory_hostname }}/cert.pem
      dest: /etc/demokit/certs/{{ inventory_hostname }}/cert.pem

  - name: copy intermediate certificate to {{ inventory_hostname }}
    copy:
      src: ../../../demos/certs/{{ inventory_hostname }}/ca.pem
      dest: /etc/demokit/certs/{{ inventory_hostname }}/ca.pem

  become: true
