---
- import_playbook: /demokit/common/command_line.yml
  vars:
    title: Install K8s on Docker CE 17.06
    limit_to_tags:
      - k8s

- import_playbook: /demokit/aws/run.yml
  tags: instances

- import_playbook: /demokit/k8s/k8s.yml
