---
- name: check required variables
  fail:
    msg: Variable {{ item }} is not defined
  when: item not in vars
  with_items: "{{ ucp_worker_required_vars }}"

- name: check swarm status on Linux
  shell: docker info -f {% raw %}'{{ .Swarm.LocalNodeState }}'{% endraw %}
  register: swarm_status_linux
  changed_when: false
  when: ansible_os_family == 'Debian'

- name: check swarm status on Windows
  win_shell: docker info -f {% raw %}'{{ .Swarm.LocalNodeState }}'{% endraw %}
  register: swarm_status_windows
  changed_when: false
  when: ansible_os_family == 'Windows'

- include_tasks: "{{ ansible_os_family | lower }}.yml"
  when:
    - (ansible_os_family == 'Debian' and swarm_status_linux.stdout == 'inactive') or
      (ansible_os_family == 'Windows' and swarm_status_windows.stdout | trim == 'inactive')
