---
- name: check required variables
  fail:
    msg: Variable {{ item }} is not defined
  when: item not in vars
  with_items: "{{ ucp_worker_required_vars }}"

- name: check swarm status on Linux
  shell: docker info -f {% raw %}'{{ .Swarm.LocalNodeState }}'{% endraw %}
  register: swarm_status
  changed_when: false
  when: ansible_os_family == 'Debian'

- name: check swarm status on Windows
  win_shell: docker info -f {% raw %}'{{ .Swarm.LocalNodeState }}'{% endraw %}
  register: swarm_status
  changed_when: false
  when: ansible_os_family == 'Windows'

- include_tasks: "{{ ansible_os_family | lower }}.yml"
  when: swarm_status.stdout | trim  == "inactive"
