---
- name: configure AWS
  hosts: localhost
  gather_facts: false
  roles:
    - role: aws_key
    - role: aws_vpc
    - role: aws_security_groups
    - role: aws_route53_letsencrypt
  vars_files:
    - /bind/settings/aws_route53_letsencrypt.yml
    - /bind/settings/aws_security_groups.yml
