---
- name: destroy AWS infrastructure
  hosts: localhost
  gather_facts: false
  roles:
    - role: aws_key
      aws_key_state: absent

    - role: aws_route53
      aws_route53_state: all_records_absent

    - role: aws_security_groups
      aws_security_groups_state: absent

    - role: aws_vpc
      aws_vpc_state: absent
