---
- name: destroy AWS infrastructure
  hosts: localhost
  gather_facts: false
  roles:
    - role: aws_ec2
      aws_ec2_state: terminated
      aws_ec2_wait: true

    - role: aws_key
      aws_key_state: absent

    - role: aws_route53_records
      aws_route53_records_state: all_records_absent

    - role: aws_security_groups
      aws_security_groups_state: absent

    - role: aws_vpc
      aws_vpc_state: absent
  vars_files:
    - /bind/settings/aws_ec2.yml
    - /bind/settings/aws_security_groups.yml
