---
- name: run ec2 instances, configure DNS, set hostnames
  hosts: localhost
  gather_facts: false
  tasks:
    - name: run ec2 instances
      import_role:
        name: aws_ec2
      vars:
        aws_ec2_limit_tags: "{{ limit | default([]) }}"

    - meta: refresh_inventory

    - name: configure dns
      import_role:
        name: aws_route53_records
  vars_files:
    - /bind/settings/aws_ec2.yml

- name: wait for instances
  hosts: >-
    ec2
    {% for tag in hostvars['localhost'].limit | default([]) -%}
      {{ ':&tag_' + tag }}
    {% endfor -%}
  gather_facts: false
  tasks:
    - name: wait for SSH/WinRM
      wait_for_connection:

- name: set hostname
  hosts: >-
    ec2
    {% for tag in hostvars['localhost'].limit | default([]) -%}
      {{ ':&tag_' + tag }}
    {% endfor -%}
  tasks:
    - import_role:
        name: set_hostname
