---
- name: run ec2 instances, configure DNS, set hostnames
  hosts: localhost
  gather_facts: false
  tasks:
    - name: run ec2 instances
      import_role:
        name: aws_ec2
      vars:
        aws_ec2_limit_tag: "{{ limit | default(None) }}"

    - meta: refresh_inventory

    - name: configure dns
      import_role:
        name: aws_route53_records
  vars_files:
    - ../demos/settings/aws_ec2.yml

- name: wait for instances
  hosts: >-
    ec2
    {% if limit is defined -%}
      {{ ':&tag_' + limit }}
    {% endif -%}
  gather_facts: false
  tasks:
    - name: wait for SSH/WinRM
      wait_for_connection:

- name: set hostname
  hosts: >-
    ec2
    {% if limit is defined -%}
      {{ ':&tag_' + limit }}
    {% endif -%}
  tasks:
    - import_role:
        name: set_hostname
