---
- name: run ec2 instances, configure DNS, set hostnames
  hosts: localhost
  gather_facts: false
  tasks:
    - name: run ec2 instances
      import_role:
        name: aws_ec2
      vars:
        aws_ec2_limit_tag: "{{ limit | default(None) }}"

    - meta: refresh_inventory

    - name: configure dns
      import_role:
        name: aws_route53

- name: wait for instances
  hosts: "{{ 'tag_' + limit | default('ec2') }}"
  gather_facts: false
  tasks:
    - name: wait for SSH/WinRM
      wait_for_connection:

- name: set hostname
  hosts: "{{ 'tag_' + limit | default('ec2') }}"
  tasks:
    - import_role:
        name: set_hostname
