---
- name: bring up ec2 instances
  hosts: localhost
  gather_facts: false
  roles:
    - aws_ec2
  tags: ec2

- name: refresh in-memory inventory
  hosts: localhost
  gather_facts: false
  tasks:
    - meta: refresh_inventory
  tags: ec2

- name: assign dns
  hosts: localhost
  gather_facts: false
  roles:
    - aws_route53
  tags: route53

- name: wait for instances to boot
  hosts: ec2
  gather_facts: false
  tasks:
    - name: wait for SSH/WinRM
      wait_for_connection:
  tags: wait
