---
- name: stop ec2 instances
  hosts: localhost
  gather_facts: false
  tasks:
    - import_role:
        name: aws_ec2
      vars:
        aws_ec2_limit_tag: "{{ limit | default(None) }}"
        aws_ec2_state: stopped
