---
- name: terminate ec2 instances
  hosts: localhost
  gather_facts: false
  tasks:
    - import_role:
        name: aws_ec2
      vars:
        aws_ec2_limit_tags: "{{ limit | default(None) }}"
        aws_ec2_state: terminated
  vars_files:
    - /bind/settings/aws_ec2.yml
