---
- name: create ucp-controller-server-certs volume
  docker_volume:
    name: ucp-controller-server-certs

- name: copy certificates and key into ucp-controller-server-certs volume
  docker_container:
    cleanup: true
    command:
      - sh -c "
        cp /src/key.pem /dst/key.pem &&
        cp /src/cert.pem /dst/cert.pem &&
        cp /src/ca.pem /dst/ca.pem"
    detach: false
    name: copy_certs
    image: alpine
    volumes:
      - /etc/demokit/certs/{{ inventory_hostname }}:/src
      - ucp-controller-server-certs:/dst
