---
- name: install Docker
  hosts: ec2
  roles:
    - set_hostname
    - docker_py
    - docker_ee_engine
  tags:
    - engine

- name: install UCP
  hosts: "{{ groups['tag_manager_nodes'] | first }}"
  roles:
    - role: ucp
      ucp_license: "{{ lookup('file', docker_ee_license_file) | to_json }}"
      ucp_san: "{{ groups['tag_manager_nodes'] | first }}"
  tags:
    - ucp

- name: join nodes to the cluster
  hosts: tag_worker_nodes
  roles:
    - role: ucp_worker
      ucp_worker_ucp_manager_group: tag_manager_nodes
  tags:
    - workers

- name: install DTR
  hosts: tag_registry_nodes
  roles:
    - role: dtr
      dtr_ucp_node: "{{ groups['tag_registry_nodes'] | first }}"
  tags:
    - dtr
