---
- name: install Docker
  hosts: >-
    tag_manager_nodes:tag_worker_nodes
    {% if limit is defined -%}
      {{ ':&tag_' + limit }}
    {% endif -%}
  roles:
    - docker_ee_engine
  tags:
    - engine

- name: install UCP
  hosts: >-
    tag_manager_nodes[0]
    {% if limit is defined -%}
      {{ ':&tag_' + limit }}
    {% endif -%}
  roles:
    - role: ucp
      ucp_license: "{{ lookup('file', docker_ee_license_file) | to_json }}"
  tags:
    - ucp

- name: join worker nodes
  hosts: >-
    tag_worker_nodes
    {% if limit is defined -%}
      {{ ':&tag_' + limit }}
    {% endif -%}
  roles:
    - role: ucp_worker
      ucp_worker_ucp_manager_group: tag_manager_nodes
  tags:
    - workers

- name: install DTR
  hosts: >-
    tag_registry_nodes
    {% if limit is defined -%}
      {{ ':&tag_' + limit }}
    {% endif -%}
  roles:
    - role: dtr
      dtr_ucp_node: "{{ hostvars[groups['tag_registry_nodes'] | first].inventory_hostname_short }}"
  tags:
    - dtr
