---
- name: pull DTR install image
  docker_image:
    name: "docker/dtr:{{ dtr_version }}"

- block:

  - name: install DTR
    docker_container:
      command:
        - install
        - "--ucp-node {{ dtr_ucp_node }}"
        - "--replica-http-port {{ dtr_replica_http_port }}"
        - "--replica-https-port {{ dtr_replica_https_port }}"
        - "--ucp-insecure-tls"
        - "--dtr-external-url {{ dtr_external_url }}"
#        - "--dtr-external-url https://dtr1.{{ demo_domain }}:{{ dtr_replica_https_port }}"
        - "--ucp-url {{ dtr_ucp_url }}"
        - "--ucp-username admin"
        - "--ucp-password {{ dtr_ucp_password }}"
      detach: false
      name: dtr
      image: "docker/dtr:{{ dtr_version }}"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock

  - name: wait for DTR install to finish
    wait_for:
      port: "{{ dtr_replica_https_port }}"
      state: started

  when: true #TODO what check should be made here?
