---
- name: check required variables
  fail:
    msg: Variable {{ item }} is not defined
  when: item not in vars
  with_items: "{{ dtr_required_vars }}"

- name: check if DTR is installed
  shell: docker ps --filter name=dtr-registry -q
  register: registry_container_id
  changed_when: false

- include_tasks: install.yml
  when: registry_container_id.stdout_lines | count == 0
