---
- name: install Docker engine
  hosts: >-
    tag_ee
    {% for tag in limit | default([]) %}
      {{ ':&tag_' + tag }}
    {% endfor %}
  roles:
    - docker_ee_engine
  tags:
    - engine
  vars_files:
    - /bind/settings/docker_ee.yml

- name: install UCP
  hosts: >-
    tag_ee:&tag_manager_nodes[0]
    {% for tag in limit | default([]) %}
      {{ ':&tag_' + tag }}
    {% endfor %}
  roles:
    - role: copy_cert
    - role: ucp_manager
      ucp_certs: true
      ucp_license: "{{ lookup('file', '/bind/licenses/docker_subscription.lic') | to_json }}"
  tags:
    - ucp
  vars_files:
    - /bind/settings/docker_ee.yml

- name: join worker nodes
  hosts: >-
    tag_ee:&tag_worker_nodes
    {% for tag in limit | default([]) %}
      {{ ':&tag_' + tag }}
    {% endfor %}
  roles:
    - role: ucp_worker
      ucp_worker_ucp_manager_group: tag_manager_nodes
  tags:
    - workers
  vars_files:
    - /bind/settings/docker_ee.yml

- name: install DTR
  hosts: >-
    tag_ee:&tag_registry_nodes[0]
    {% for tag in limit | default([]) %}
      {{ ':&tag_' + tag }}
    {% endfor %}
  roles:
    - role: dtr
      dtr_ca: '"{{ lookup("file", "/bind/certs/" + inventory_hostname + "/ca.pem") }}"'
      dtr_cert: '"{{ lookup("file", "/bind/certs/" + inventory_hostname + "/cert.pem") }}"'
      dtr_key: '"{{ lookup("file", "/bind/certs/" + inventory_hostname + "/key.pem") }}"'
      dtr_ucp_node: "{{ hostvars[groups['tag_registry_nodes'] | first].inventory_hostname_short }}"
  tags:
    - dtr
  vars_files:
    - /bind/settings/docker_ee.yml

# - name: configure UCP and DTR
#   hosts: localhost
#   gather_facts: false
#   tasks:
#     - import_role:
#         name: ucp_config
#     - import_role:
#         name: dtr_config
#   tags:
#     - config
#   vars_files:
#     - /bind/settings/docker_ee.yml

- name: populate UCP with demo data
  hosts: localhost
  gather_facts: false
  tasks:
    - include_role:
        name: ucp_rbac
      when: docker_ee_populate and 'windows' not in limit
  tags:
    - populate
    - populate_ucp
  vars_files:
    - /bind/settings/docker_ee.yml
    - /bind/settings/ucp_rbac.yml

- name: populate DTR with demo data
  hosts: >-
    tag_ee:&tag_registry_nodes[0]
    {% for tag in limit | default([]) %}
      {{ ':&tag_' + tag }}
    {% endfor %}
  gather_facts: false
  tasks:
    - include_role:
        name: dtr_repos
      when: docker_ee_populate
  tags:
    - populate
    - populate_dtr
  vars_files:
    - /bind/settings/docker_ee.yml
    - /bind/settings/dtr_repos.yml