---
aws_vpc_cidr_block: "172.31.0.0/16"
aws_vpc_name: ""
aws_vpc_profile: "{{ aws_profile }}"
aws_vpc_region: "{{ aws_region }}"
aws_vpc_subnet: "172.31.0.0/20"
aws_vpc_state: present
aws_vpc_tags: "{{ aws_tags }}"
