---
- name: generates aws filter
  set_fact:
    aws_ec2_tags_formatted: >
      {{ aws_ec2_tags_formatted | default({}) | combine(
          { 'tag:' + item.key: item.value }
        )
      }}
  loop_control:
    label: "{{ item.key }}"
  with_dict: "{{ aws_ec2_tags }}"

- name: find tagged ec2 instances
  ec2_instance_facts:
    filters: "{{ aws_ec2_tags_formatted }}"
    profile: "{{ aws_ec2_profile }}"
    region: "{{ aws_ec2_region }}"
  register: find_ec2

- include_tasks: "{{ aws_ec2_state }}.yml"
