---
- name: terminate ec2 instances
  ec2_instance:
    instance_ids: "{{ item.instance_id }}"
    profile: "{{ aws_ec2_profile }}"
    region: "{{ aws_ec2_region }}"
    state: 'absent'
    wait: no
  loop: >
    {{
      find_ec2.instances | selectattr('state.name', 'equalto', 'running') | list
      + find_ec2.instances | selectattr('state.name', 'equalto', 'stopped') | list
    }}
  loop_control:
    label: "{{ item.tags.Name }}"
