---
- name: check if UCP is installed
  shell: docker ps --filter name=ucp-controller -q
  register: ucp_controller_container_id
  changed_when: false

- include_tasks: install.yml
  when: ucp_controller_container_id.stdout_lines | count == 0
