---
- name: install the DockerProvider module
  win_psmodule:
    name: DockerProvider

- name: install Docker EE
  win_dsc:
    ensure: present
    name: Docker
    ProviderName: DockerProvider
    RequiredVersion: "{{ docker_ee_engine_windows_version | default(omit, true) }}"
    Source: Docker
    resource_name: PackageManagement

- name: start the Docker service
  win_service:
    name: Docker
    state: started
  failed_when: false
  register: service_result

- name: reboot to complete the install if the service didn't start
  win_shell: Restart-Computer -Force
  when: service_result.state == 'stopped'
