---
- hosts: localhost
  gather_facts: false
  vars_files:
    - answers.yml
  tasks:

    - name: ec2.py -- ec2 dynamic inventory script
      template:
        mode: a+x
        src: files/ec2.py
        dest: ../inventory/ec2.py

    - name: ec2.ini -- ec2 dynamic inventory configuration
      template:
        backup: yes
        src: templates/ec2.ini.j2
        dest: ../inventory/ec2.ini

    - name: all.yml -- group variables across all inventory
      template:
        backup: yes
        src: templates/all.yml.j2
        dest: ../inventory/group_vars/all.yml

    - name: aws_ec2.yml -- AWS EC2 instance settings
      copy:
        backup: yes
        src: files/aws_ec2.yml
        dest: ../demos/settings/aws_ec2.yml

    - name: aws_security_groups.yml -- AWS Security Group settings
      copy:
        backup: yes
        src: files/aws_security_groups.yml
        dest: ../demos/settings/aws_security_groups.yml

    - name: docker_ee.yml -- Docker EE settings
      template:
        backup: yes
        src: templates/docker_ee.yml.j2
        dest: ../demos/settings/docker_ee.yml

    - name: ucp_rbac.yml -- UCP RBAC settings
      template:
        backup: yes
        src: files/ucp_rbac.yml
        dest: ../demos/settings/ucp_rbac.yml

    - name: dtr_repos.yml -- DTR repositories settings
      template:
        backup: yes
        src: files/dtr_repos.yml
        dest: ../demos/settings/dtr_repos.yml
