---
- name: install Docker engine
  hosts: >-
    tag_manager_nodes:tag_worker_nodes
    {% if limit is defined -%}
      {{ ':&tag_' + limit }}
    {% endif -%}
  roles:
    - docker_ee_engine
  tags:
    - engine
  vars_files:
    - ../demos/settings/docker_ee.yml

- name: install UCP
  hosts: >-
    tag_manager_nodes[0]
    {% if limit is defined -%}
      {{ ':&tag_' + limit }}
    {% endif -%}
  roles:
    - role: ucp_manager
      ucp_license: "{{ lookup('file', docker_ee_license_file) | to_json }}"
  tags:
    - ucp
  vars_files:
    - ../demos/settings/docker_ee.yml

- name: join worker nodes
  hosts: >-
    tag_worker_nodes
    {% if limit is defined -%}
      {{ ':&tag_' + limit }}
    {% endif -%}
  roles:
    - role: ucp_worker
      ucp_worker_ucp_manager_group: tag_manager_nodes
  tags:
    - workers
  vars_files:
    - ../demos/settings/docker_ee.yml

- name: install DTR
  hosts: >-
    tag_registry_nodes[0]
    {% if limit is defined -%}
      {{ ':&tag_' + limit }}
    {% endif -%}
  roles:
    - role: dtr
      dtr_ucp_node: "{{ hostvars[groups['tag_registry_nodes'] | first].inventory_hostname_short }}"
  tags:
    - dtr
  vars_files:
    - ../demos/settings/docker_ee.yml

# - name: configure UCP and DTR
#   hosts: localhost
#   gather_facts: false
#   tasks:
#     - import_role:
#         name: ucp_config
#     - import_role:
#         name: dtr_config
#   tags:
#     - config
#   vars_files:
#     - ../demos/settings/docker_ee.yml

- name: populate UCP with demo data
  hosts: localhost
  gather_facts: false
  tasks:
    - include_role:
        name: ucp_rbac
      when: docker_ee_populate and limit != 'windows'
  tags:
    - populate
    - populate_ucp
  vars_files:
    - ../demos/settings/docker_ee.yml
    - ../demos/settings/ucp_rbac.yml

- name: populate DTR with demo data
  hosts: >-
    tag_registry_nodes[0]
    {% if limit is defined -%}
      {{ ':&tag_' + limit }}
    {% endif -%}
  gather_facts: false
  tasks:
    - include_role:
        name: dtr_repos
      when: docker_ee_populate
  tags:
    - populate
    - populate_dtr
  vars_files:
    - ../demos/settings/docker_ee.yml
    - ../demos/settings/dtr_repos.yml
