- name: create teams
  uri:
    body:
      name: "{{ item.1.team | default(item.1) }}"
    body_format: json
    headers:
      Authorization: Bearer {{ ucp_token }}
    method: POST
    status_code: 201
    url: "{{ ucp_url }}/accounts/{{ item.0.org }}/teams"
    validate_certs: false
  changed_when: uri_result.status == 201
  failed_when: >
    uri_result.status != 201
    and
    'TEAM_EXISTS' not in uri_result.json.errors | map(attribute='code') | list
  loop: >
    {{
      q('subelements', ucp_rbac_orgs | select('mapping') | list, 'teams', { 'skip_missing':True })
    }}
  loop_control:
    label: "{{ item.0.org + '->' + item.1.team | default(item.1) }}"
  register: uri_result
  when: item.1.team is defined
